name: Release
on: {}
  # push:
  #   tags:
  #     - "v*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7
    permissions:
      contents: write
    with:
      release_files: rules_pydeps-*.tar.gz
      prerelease: false
